name: Coverity Scan
on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/javascript/linux64 --post-data "token=$TOKEN&project=Zialus%2FTW-Minesweeper-Client" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cd src
          cov-build --dir cov-int --no-command --fs-capture-search ./

      - name: Submit the result to Coverity Scan
        run: |
          cd src
          tar czvf sweeper.tgz cov-int
          curl \
          --form token=$TOKEN \
          --form email=raulmendesferreira@gmail.com \
          --form file=@sweeper.tgz \
          --form version="trunk" \
          --form description="Minesweeper-Client" \
          https://scan.coverity.com/builds?project=Zialus%2FTW-Minesweeper-Client
        env:
          TOKEN: ${{ secrets.COVERITY_TOKEN }}
